name: Benchmark

on: 
  workflow_dispatch:
  push:
    branches: [ main ]
    
jobs:
  build-and-benchmark:
  
    runs-on: windows-2022
    
    steps:
    - uses: actions/checkout@v3.3.0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 6.0.x
    - name: Restore NuGet
      run: dotnet restore
    - name: Build 
      run: dotnet build --configuration=Release --no-restore 
    - name: Benchmark 
      run: Benchmark.exe
