name: Unit Tests

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3.3.0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration=Debug --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity=normal
